/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jogo;

/**
 *
 * @author Othavio
 */
public class TelaDeFase6Nivel2 extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeFase6Nivel2
     */
    public TelaDeFase6Nivel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTelaFase6Nivel2 = new javax.swing.JPanel();
        perguntaLabel = new javax.swing.JLabel();
        primeiraReposta = new javax.swing.JButton();
        segundaReposta = new javax.swing.JButton();
        terceiraReposta = new javax.swing.JButton();
        quartaReposta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelTelaFase6Nivel2.setBackground(new java.awt.Color(0, 0, 45));

        perguntaLabel.setBackground(new java.awt.Color(0, 0, 45));
        perguntaLabel.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        perguntaLabel.setForeground(new java.awt.Color(255, 255, 255));
        perguntaLabel.setText("Espaço para pergunta");

        primeiraReposta.setBackground(new java.awt.Color(0, 0, 0));
        primeiraReposta.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        primeiraReposta.setForeground(new java.awt.Color(255, 255, 255));
        primeiraReposta.setText("Espaço para reposta");

        segundaReposta.setBackground(new java.awt.Color(0, 0, 0));
        segundaReposta.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        segundaReposta.setForeground(new java.awt.Color(255, 255, 255));
        segundaReposta.setText("Espaço para reposta");

        terceiraReposta.setBackground(new java.awt.Color(0, 0, 0));
        terceiraReposta.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        terceiraReposta.setForeground(new java.awt.Color(255, 255, 255));
        terceiraReposta.setText("Espaço para reposta");

        quartaReposta.setBackground(new java.awt.Color(0, 0, 0));
        quartaReposta.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        quartaReposta.setForeground(new java.awt.Color(255, 255, 255));
        quartaReposta.setText("Espaço para reposta");

        javax.swing.GroupLayout painelTelaFase6Nivel2Layout = new javax.swing.GroupLayout(painelTelaFase6Nivel2);
        painelTelaFase6Nivel2.setLayout(painelTelaFase6Nivel2Layout);
        painelTelaFase6Nivel2Layout.setHorizontalGroup(
            painelTelaFase6Nivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelaFase6Nivel2Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(painelTelaFase6Nivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(perguntaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelTelaFase6Nivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(painelTelaFase6Nivel2Layout.createSequentialGroup()
                            .addComponent(terceiraReposta, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quartaReposta, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(painelTelaFase6Nivel2Layout.createSequentialGroup()
                            .addComponent(primeiraReposta, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(182, 182, 182)
                            .addComponent(segundaReposta, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        painelTelaFase6Nivel2Layout.setVerticalGroup(
            painelTelaFase6Nivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelaFase6Nivel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(perguntaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(painelTelaFase6Nivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primeiraReposta, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(segundaReposta, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(painelTelaFase6Nivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(terceiraReposta, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quartaReposta, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelTelaFase6Nivel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelTelaFase6Nivel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeFase6Nivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeFase6Nivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeFase6Nivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeFase6Nivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeFase6Nivel2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel painelTelaFase6Nivel2;
    private javax.swing.JLabel perguntaLabel;
    private javax.swing.JButton primeiraReposta;
    private javax.swing.JButton quartaReposta;
    private javax.swing.JButton segundaReposta;
    private javax.swing.JButton terceiraReposta;
    // End of variables declaration//GEN-END:variables
}
