/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jogo;

/**
 *
 * @author Othavio
 */
public class TelaMaterialIfElifElse extends javax.swing.JFrame {

    /**
     * Creates new form TelaMaterialIfElifElse
     */
    public TelaMaterialIfElifElse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMaterialIfElifElse = new javax.swing.JPanel();
        ifElifElseLabel = new javax.swing.JLabel();
        voltarLabel = new javax.swing.JLabel();
        materialLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelMaterialIfElifElse.setBackground(new java.awt.Color(0, 0, 45));
        painelMaterialIfElifElse.setPreferredSize(new java.awt.Dimension(1128, 720));

        ifElifElseLabel.setBackground(new java.awt.Color(0, 0, 45));
        ifElifElseLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ifElifElseLabel.setForeground(new java.awt.Color(187, 187, 187));
        ifElifElseLabel.setText("If/Elif/Else");

        voltarLabel.setText("jLabel2");

        materialLabel.setText("jLabel1");

        javax.swing.GroupLayout painelMaterialIfElifElseLayout = new javax.swing.GroupLayout(painelMaterialIfElifElse);
        painelMaterialIfElifElse.setLayout(painelMaterialIfElifElseLayout);
        painelMaterialIfElifElseLayout.setHorizontalGroup(
            painelMaterialIfElifElseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMaterialIfElifElseLayout.createSequentialGroup()
                .addGroup(painelMaterialIfElifElseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelMaterialIfElifElseLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(voltarLabel)
                        .addGap(346, 346, 346)
                        .addComponent(ifElifElseLabel))
                    .addGroup(painelMaterialIfElifElseLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(materialLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        painelMaterialIfElifElseLayout.setVerticalGroup(
            painelMaterialIfElifElseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMaterialIfElifElseLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(painelMaterialIfElifElseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ifElifElseLabel)
                    .addComponent(voltarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(materialLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(painelMaterialIfElifElse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(painelMaterialIfElifElse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMaterialIfElifElse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMaterialIfElifElse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMaterialIfElifElse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMaterialIfElifElse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMaterialIfElifElse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ifElifElseLabel;
    private javax.swing.JLabel materialLabel;
    private javax.swing.JPanel painelMaterialIfElifElse;
    private javax.swing.JLabel voltarLabel;
    // End of variables declaration//GEN-END:variables
}
