/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jogo;

/**
 *
 * @author mateu
 */
public class TelaDeFase1Nivel2 extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeFase1Nivel2
     */
    public TelaDeFase1Nivel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFase1Nivel2 = new javax.swing.JPanel();
        perguntaDaFase1Nivel2 = new javax.swing.JLabel();
        primeiraResposta = new javax.swing.JButton();
        segundaFase = new javax.swing.JButton();
        terceiraFase = new javax.swing.JButton();
        quartaFase = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelFase1Nivel2.setBackground(new java.awt.Color(0, 0, 45));
        painelFase1Nivel2.setPreferredSize(new java.awt.Dimension(1128, 720));

        perguntaDaFase1Nivel2.setForeground(new java.awt.Color(255, 255, 255));
        perguntaDaFase1Nivel2.setText("parte para pergunta");

        primeiraResposta.setBackground(new java.awt.Color(0, 0, 0));
        primeiraResposta.setForeground(new java.awt.Color(255, 255, 255));
        primeiraResposta.setText("parte para resposta");

        segundaFase.setBackground(new java.awt.Color(0, 0, 0));
        segundaFase.setForeground(new java.awt.Color(255, 255, 255));
        segundaFase.setText("parte para resposta");

        terceiraFase.setBackground(new java.awt.Color(0, 0, 0));
        terceiraFase.setForeground(new java.awt.Color(255, 255, 255));
        terceiraFase.setText("parte para resposta");

        quartaFase.setBackground(new java.awt.Color(0, 0, 0));
        quartaFase.setForeground(new java.awt.Color(255, 255, 255));
        quartaFase.setText("parte para resposta");
        quartaFase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quartaFaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelFase1Nivel2Layout = new javax.swing.GroupLayout(painelFase1Nivel2);
        painelFase1Nivel2.setLayout(painelFase1Nivel2Layout);
        painelFase1Nivel2Layout.setHorizontalGroup(
            painelFase1Nivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFase1Nivel2Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(painelFase1Nivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(perguntaDaFase1Nivel2, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelFase1Nivel2Layout.createSequentialGroup()
                        .addGroup(painelFase1Nivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(primeiraResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(terceiraFase, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(182, 182, 182)
                        .addGroup(painelFase1Nivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(segundaFase, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                            .addComponent(quartaFase, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        painelFase1Nivel2Layout.setVerticalGroup(
            painelFase1Nivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFase1Nivel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(perguntaDaFase1Nivel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelFase1Nivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primeiraResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(segundaFase, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelFase1Nivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(terceiraFase, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(quartaFase, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelFase1Nivel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelFase1Nivel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quartaFaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quartaFaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quartaFaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeFase1Nivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeFase1Nivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeFase1Nivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeFase1Nivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeFase1Nivel2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel painelFase1Nivel2;
    private javax.swing.JLabel perguntaDaFase1Nivel2;
    private javax.swing.JButton primeiraResposta;
    private javax.swing.JButton quartaFase;
    private javax.swing.JButton segundaFase;
    private javax.swing.JButton terceiraFase;
    // End of variables declaration//GEN-END:variables
}
